name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Download repository
      - uses: actions/checkout@v4

      # Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Chrome
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      # Setup gradlew permission
      - name: Setup Gradlew
        run: chmod +x gradlew

      # Run Gradle test with xvfb (virtual display for headless browser)
      - name: Execute Test
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" ./gradlew clean test

      # Archive Cucumber report
      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cucumber Report
          path: reports/cucumber-report.html
