name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # download repo
      - uses: actions/checkout@v4

      # setup java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Chrome
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      # Install ChromeDriver (sinkron dengan Chrome)
      - name: Setup Chrome + ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
          install-chromedriver: true


      # setup gradlew
      - name: setup gradlew
        run: chmod +x gradlew

      # execute gradle command for running cucumber test
      - name: Execute Test
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" ./gradlew clean test

      # Archive Test Result
      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cucumber Report
          path: build/reports/tests/test

      # Archive Cucumber HTML Report
      - name: Archive Cucumber HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cucumber HTML Report
          path: build/cucumber-html-reports